### ISSUE TITLE
Missing seeds affecting default admin account (lack thereof) and some translations

### ISSUE THREAD

**Issue by shun-yoshida** [etewiah/pwb-for-heroku#1]
Hi Ed. I have deployed this repository onto _Heroku_ and I think the entire "seeds" inside _/db_ is missing as compared to the primary repository here:
https://github.com/etewiah/property_web_builder

As a consequence you don't get a default admin account. You can of course create a new user then change the user level with _psql_ but I don't think this is intended. Also there are some missing translations under the _New Property_ tab which can be found inside the _translations.rb_ file in the original repository.

Is there any reason why you are maintaining these as two separate repositories?

**Comment by etewiah** [comment]
Hello Shun, thanks for having a look.  The reason for the two separate repositories is that the main application is a rails engine that cannot be deployed directly to a server.  This project is a rails application that uses the PropertyWebBuilder engine.  You can learn more about Rails engines here:

http://railscasts.com/episodes/277-mountable-engines

This explains why the seeds directory is missing in this project.  When you run the command "rake pwb:db:seed" it will actually look for the relevant files within the engine.

Did you successfully run "rake pwb:db:seed"?  If you are deploying to heroku you will need to prefix it with "heroku run".   If you want to run it on your local database you may need to prefix it with "bundle exec".

Hope this helps.

**Comment by shun-yoshida** [comment]
Thanks. I have deployed it using the "Deploy to Heroku" link and it works fine. The link on the _property_web_builder_ kept throwing me an error so I was deploying it manually. It looks like you have already fixed the link though.

My connection was rather choppy yesterday (I am on road) so the command could have errored out. I will close the issue for now and try again once I'm home.
