### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Zaldor** [etewiah/pwb-for-heroku#3]
HI, once installed how do I update to the latest version?

**Comment by etewiah** [comment]
Hi @Zaldor, from the heroku dashboard if you select your project you will find a "deploy" tab.  Under that tab you will have the option to connect to a github repo.  Follow the instructions to connect to this repo.  
Once you do that you will have the option to manually deploy.  Using that option to deploy will update your project to the latest version.

**Comment by Zaldor** [comment]
do I have to first clone?

**Comment by Zaldor** [comment]
just forked it. thanks

**Comment by etewiah** [comment]
Yeah, I think forking it should do the trick.  Let me know if it doesn't work.

**Comment by Zaldor** [comment]
Worked perfectly from what i can see

**Comment by etewiah** [comment]
Great!
