### ISSUE TITLE
Rake aborted

### ISSUE THREAD

**Issue by Viniciusvalenca** [etewiah/pwb-for-heroku#30]
when i triy rake:seed i got this error

rake aborted!
NoMethodError: undefined method `new' for Google:Module

**Comment by etewiah** [comment]
Hi @Viniciusvalenca, I have changed PropertyWebBuilder from a Rails engine to a standalone project. 

You can now deploy it directly from the main project [PropertyWebBuilder](https://etewiah.github.io/property_web_builder/). Please try it out and let me know how it goes.
