### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Zaldor** [etewiah/pwb-for-heroku#4]
I would love to help out with the project, and as you said thw documentation could be a starting point, but at the moment is not very clear how will that happen, (I will read more on how github works) do I have to make all the changes in my fork and wait for you to pull from it?
will the wiki be treated as code and merge to your repo with a pull request too?
looks like the first contribution could be How To Contribute Page :)
Thanks

**Comment by etewiah** [comment]
I realised I hadn't made the wiki editable by everyone which is what I want.  I've just changed that setting so you should be able to add pages and edit existing ones.  No need for pull requests etc.  Just edit directly ;)

You can find out more here:
https://help.github.com/articles/about-github-wikis/

**Comment by Zaldor** [comment]
Great!
