### ISSUE TITLE
Heroku error -  not permitted to install the sendgrid add-on at this time

### ISSUE THREAD

**Issue by etewiah** [etewiah/pwb-for-heroku#5]
Opening this issue on behalf of a user who emailed me with the following:

I'm receiving the following error during installation: The account "****@***.com" is not permitted to install the sendgrid add-on at this time. If you believe this is an error please contact support and reference ID 1e8984bd-e1f1-4daa-ba11-c86d5ee25178 when opening an ticket.

**Comment by joevago** [comment]
I am receiving the same error when trying to deploy.  Please let me know when this is resolved as I am very interested in using your application.  Thanks in advance for any help you can provide!

![heroku_deployerror](https://user-images.githubusercontent.com/6776972/35407505-351433e0-01da-11e8-9e95-99ffe67d2d3f.jpg)

**Comment by etewiah** [comment]
Hi @joevago, thanks for checking out PWB.  It seems that new users on heroku are sometimes not allowed to install the sendgrid addon:

https://stackoverflow.com/questions/48254150/heroku-not-permitted-to-install-sendgrid-addon

As a workaround I have modified the "app.json" file so it does not get deployed automatically.  The site should deploy okay but the email functionality will not work until you go to the heroku dashboard and manually add the sendgrid addon.

Please try deploying again and let me know how it goest.

**Comment by joevago** [comment]
Ed,

I was able to deploy and this looks outstanding.  I will be contacting
Heroku support today to get SendGrid installed.

One question: for the Site navbar - can your system display a Company Logo
and the Company name at the same time?  Right now only the Logo shows up.

I expect to be donating to your efforts very soon!

Joe Vago
603-867-5334 (c)
978.226.8759 (w)
www.SkyWebsites.NET <http://www.skywebsites.net/>
*Concept. Design. Build. Launch. Support.*

**Comment by etewiah** [comment]
Great, glad you hear you like it.  
Right now the navbar is as customisable through the UI as I'd like it to be.  Will make it more customisable soon but for now you can edit the template here to do what you are asking about:

https://github.com/etewiah/property_web_builder/blob/master/app/views/pwb/_header.html.erb

Cheers,

Ed
