### ISSUE TITLE
Still can't get the Bulgarian language in Admin UI working

### ISSUE THREAD

**Issue by vvalchev** [etewiah/pwb-for-heroku#9]
Recently, i've committed a patch to add Bulgarian language.
Some changes were needed to made it work in admin panel, and I actually saw the commit there.
However, when I open `/bg/admin/dashboard` I still see everything in English and the selected flag is also the British one.

Chrome web developer tools also reveals that it loads `/api/v1/translations/list/en`, while it should be 'bg'.

Here are part of the log, printed by the application:
```
D, [2018-02-27T13:56:35.168494 #42] DEBUG -- : [a3f20410-275c-498c-8ef0-d82f43811a2d]   Pwb::User Load (0.4ms)  SELECT  "pwb_users".* FROM "pwb_users" WHERE "pwb_users"."id" = $1 ORDER BY "pwb_users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
I, [2018-02-27T13:56:35.169683 #42]  INFO -- : [a3f20410-275c-498c-8ef0-d82f43811a2d] Processing by Pwb::AdminPanelController#show as HTML
I, [2018-02-27T13:56:35.169782 #42]  INFO -- : [a3f20410-275c-498c-8ef0-d82f43811a2d]   Parameters: {"locale"=>"bg", "path"=>"dashboard"}
I, [2018-02-27T13:56:35.171030 #42]  INFO -- : [a3f20410-275c-498c-8ef0-d82f43811a2d]   Rendering /usr/local/bundle/bundler/gems/property_web_builder-35846839ae41views/pwb/admin_panel/show.html.erb within layouts/pwb/admin_panel
I, [2018-02-27T13:56:35.171299 #42]  INFO -- : [a3f20410-275c-498c-8ef0-d82f43811a2d]   Rendered /usr/local/bundle/bundler/gems/property_web_builder-35846839ae41views/pwb/admin_panel/show.html.erb within layouts/pwb/admin_panel (0.1ms)
I, [2018-02-27T13:56:35.172534 #42]  INFO -- : [a3f20410-275c-498c-8ef0-d82f43811a2d] Completed 200 OK in 3ms (Views: 1.7ms | ActiveRecord: 0.0ms)
I, [2018-02-27T13:56:35.601508 #42]  INFO -- : [24f043ac-f8e8-4c0d-bb7a-cc6f20b28a70] Started GET "/api/v1/translations/list/en" for 172.17.0.1 at 2018-02-27 13:56:35 +0000
```

Could it be that the Bulgarian language got committed only in pwb, but not in pwb-for-heroku?
E.g. here -> https://github.com/etewiah/pwb-for-heroku/tree/master/public/assets/pwb_admin_panel

**Comment by etewiah** [comment]
Hi, sorry about that.  I did indeed forget to update this repo.  I'll do that now and push it out.

**Comment by etewiah** [comment]
Okay, so I've just updated that and tested it in the demo app:

https://propertywebbuilder.herokuapp.com/bg/admin/pages/contact-us/content_html

**Comment by vvalchev** [comment]
it works! thank you!
